# Generated by Django 4.2.13 on 2024-10-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Student_number',
            new_name='student_number',
        ),
    ]
